### ISSUE TITLE
Business Objectives

### ISSUE THREAD

**Issue by lupinteq** [GIT-ATHON-GROUP/AI-CareerGuide-DocumentationRepo#3]
Write down the business objectives for our project.

**Comment by MashauLW** [comment]
[objectives.pdf](https://github.com/GIT-ATHON-GROUP/AI-CareerGuide-DocumentationRepo/files/12396804/objectives.pdf)
@CodeboyTF

**Comment by CodeboyTF** [comment]
[more business objectives.pdf](https://github.com/GIT-ATHON-GROUP/AI-CareerGuide-DocumentationRepo/files/12401865/more.business.objectives.pdf)
@MashauLW

**Comment by lupinteq** [comment]
upload in the repository

**Comment by lupinteq** [comment]
Use Quillbot (https://quillbot.com/grammar-check) to fix the grammar. Select English UK then copy and paste your content, then select the highlighted words marked in red to replace with the suggested words.

**Comment by lupinteq** [comment]
Compile your work in one document, do not submit separate documents

**Comment by lupinteq** [comment]
Done!
