### ISSUE TITLE
Problem Definition

### ISSUE THREAD

**Issue by lupinteq** [GIT-ATHON-GROUP/AI-CareerGuide-DocumentationRepo#4]
Write a problem definition for our project. (What is the problem? How beneficial will it be in solving the problem?  Must be found when reading the problem definition.)

**Comment by NathanTshiteya** [comment]
[PROBLEM_DEF.docx](https://github.com/GIT-ATHON-GROUP/AI-CareerGuide-DocumentationRepo/files/12357905/PROBLEM_DEF.docx)

**Comment by lupinteq** [comment]
Fix the grammar using https://quillbot.com/grammar-check, change language to British English

**Comment by NathanTshiteya** [comment]
I don't see British language, it's only English US

**Comment by NathanTshiteya** [comment]
There are no errors I just checked there in quillbot-grammer checker

**Comment by lupinteq** [comment]
There are no errors because you are using English US. You must sign in first to get the privilege to switch languages. Use Gmail to sign in, then change the language to British English after you copy and paste your content.

**Comment by NathanTshiteya** [comment]
I already signed in but I don't see British English bro

**Comment by NathanTshiteya** [comment]
[PROBLEM DEFINITION.pdf](https://github.com/GIT-ATHON-GROUP/AI-CareerGuide-DocumentationRepo/files/12380874/PROBLEM.DEFINITION.pdf)

Here it is. corrected in British English!

**Comment by lupinteq** [comment]
Completed!
