### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by lupinteq** [GIT-ATHON-GROUP/AI-CareerGuide-DocumentationRepo#5]
Define the System Requirements

**Comment by Fhulu1** [comment]
[Career guidance software requirements.txt](https://github.com/GIT-ATHON-GROUP/AI-CareerGuide-DocumentationRepo/files/12407825/Career.guidance.software.requirements.txt)

**Comment by lupinteq** [comment]
Please upload your text file in the repository, create a pull request, then create a sub-branch and upload your txt file

**Comment by lupinteq** [comment]
Done!

**Comment by lupinteq** [comment]
done!
