### ISSUE TITLE
Constraints & Risks

### ISSUE THREAD

**Issue by lupinteq** [GIT-ATHON-GROUP/AI-CareerGuide-DocumentationRepo#6]
Define the constraints & risks for our project.

**Comment by Tshepo-Mzimba** [comment]
Risks
- Privacy Violations
- socioeconomic inequality
- Loss of human influence
- Self-aware AI not controlled
- Market volatility

**Comment by lupinteq** [comment]
Please elaborate

**Comment by Tshepo-Mzimba** [comment]
Risks
- Privacy Violations.
 AI can be used to create highly sophisticated phishing attacks, which can trick users into revealing sensitive information or clicking malicious links.
- Socioeconomic inequality.
 AI can reduce the relative amount of income going to low-skilled labour, which will increase inequality across society
- Loss of human influence.
 AI significantly impacts the loss of human decision-making and makes human lazy.
- Self-aware AI not controlled.
 If AI systems attain self-awareness, their behaviour could become unpredictable and end up acting in ways that humans cannot anticipate or control.
- Market volatility.
 People often think about volatility only when prices fall, however volatility can also refer to sudden price rises too, and find that the user cannot afford.

**Comment by Tshepo-Mzimba** [comment]
@OctoberTwenty4th please do the constraints fellow

**Comment by lupinteq** [comment]
Done!
